version: '3.9'

networks:
  itorum:
    driver: bridge

services:
  database:
    container_name: itorum-db
    image: postgres:17.5
    stop_signal: SIGKILL
    restart: always
    env_file:
      - '.env'
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - ./database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DATA}
    networks:
      - itorum
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${PG_DATA} -U ${PG_USER}']
      interval: 60s
      timeout: 60s
      retries: 5

  redis:
    container_name: itorum-redis
    image: redis:8.0.2
    stop_signal: SIGKILL
    env_file:
      - '.env'
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - itorum
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 60s
      retries: 5

  celery_worker:
    container_name: itorum-celery-worker
    build:
      context: ./src
      dockerfile: Dockerfile
    command: celery -A core worker -l info
    stop_signal: SIGKILL
    volumes:
      - ./src:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://redis:${REDIS_PORT}/0
    networks:
      - itorum
    healthcheck:
      test: ["CMD-SHELL", "celery -A core inspect ping --destination celery@${HOSTNAME} || exit 1"]
      interval: 60s
      timeout: 60s
      retries: 5

  celery_beat:
    container_name: itorum-celery-beat
    build:
      context: ./src
      dockerfile: Dockerfile
    command: celery -A core beat -l info
    stop_signal: SIGKILL
    volumes:
      - ./src:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://redis:${REDIS_PORT}/0
    networks:
      - itorum
    healthcheck:
      test: ["CMD-SHELL", "celery -A core inspect ping --destination celery@${HOSTNAME} || exit 1"]
      interval: 60s
      timeout: 60s
      retries: 5

  backend:
    container_name: itorum-back
    build:
      context: ./src
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    stop_signal: SIGKILL
    env_file:
      - '.env'
    environment:
      - PG_HOST=database
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://redis:${REDIS_PORT}/0
    ports:
      - '${APP_PORT}:8000'
    networks:
      - itorum
    depends_on:
      - database
      - redis
      - celery_worker
      - celery_beat
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/events/ || exit 1"]
      interval: 60s
      timeout: 60s
      retries: 5
