# Generated by Django 5.2.1 on 2025-06-08 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(choices=[(1, 'pending'), (2, 'completed'), (3, 'cancelled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_timestamp', models.BigIntegerField(db_index=True, default=0)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('status', 'sort_timestamp'),
            },
        ),
    ]
